apiVersion: v1
kind: Service
metadata:
  name: cryptoxai-service
spec:
  selector:
    app: cryptoxai
  ports:
    - name: cryptoapp-port
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30007
    - name: pluginbackend-port
      protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30008
  type: NodePort
